export const geography = {
  countries: [
    {name: 'Ireland', iso_code: 'IE'},
    {name: 'Italy', iso_code: 'IT', state_label: 'Province', states: [
      {name: 'Agrigento', iso_code: 'AG'},
      {name: 'Alessandria', iso_code: 'AL'},
      {name: 'Ancona', iso_code: 'AN'},
      {name: 'Aosta', iso_code: 'AO'},
      {name: 'Arezzo', iso_code: 'AR'},
      {name: 'Ascoli', iso_code: 'Pi'},
      {name: 'Asti', iso_code: 'AT'},
      {name: 'Avellino', iso_code: 'AV'},
      {name: 'Bari', iso_code: 'BA'},
      {name: 'Barletta-Andria-Trani', iso_code: 'BT'},
      {name: 'Belluno', iso_code: 'BL'},
      {name: 'Benevento', iso_code: 'BN'},
      {name: 'Bergamo', iso_code: 'BG'},
      {name: 'Biella', iso_code: 'BI'},
      {name: 'Bologna', iso_code: 'BO'},
      {name: 'Bolzano[Note 1]', iso_code: 'BZ'},
      {name: 'Brescia', iso_code: 'BS'},
      {name: 'Brindisi', iso_code: 'BR'},
      {name: 'Cagliari', iso_code: 'CA'},
      {name: 'Caltanissetta', iso_code: 'CL'},
      {name: 'Campobasso', iso_code: 'CB'},
      {name: 'Carbonia-Iglesias', iso_code: 'CI'},
      {name: 'Caserta', iso_code: 'CE'},
      {name: 'Catania', iso_code: 'CT'},
      {name: 'Catanzaro', iso_code: 'CZ'},
      {name: 'Chieti', iso_code: 'CH'},
      {name: 'Como', iso_code: 'CO'},
      {name: 'Cosenza', iso_code: 'CS'},
      {name: 'Cremona', iso_code: 'CR'},
      {name: 'Crotone', iso_code: 'KR'},
      {name: 'Cuneo', iso_code: 'CN'},
      {name: 'Enna', iso_code: 'EN'},
      {name: 'Fermo', iso_code: 'FM'},
      {name: 'Ferrara', iso_code: 'FE'},
      {name: 'Florence', iso_code: 'FI'},
      {name: 'Foggia', iso_code: 'FG'},
      {name: 'Forlì-Cesena', iso_code: 'FC'},
      {name: 'Frosinone', iso_code: 'FR'},
      {name: 'Genoa', iso_code: 'GE'},
      {name: 'Gorizia', iso_code: 'GO'},
      {name: 'Grosseto', iso_code: 'GR'},
      {name: 'Imperia', iso_code: 'IM'},
      {name: 'Isernia', iso_code: 'IS'},
      {name: 'La', iso_code: 'Sp'},
      {name: 'L\'Aquila', iso_code: 'AQ'},
      {name: 'Latina', iso_code: 'LT'},
      {name: 'Lecce', iso_code: 'LE'},
      {name: 'Lecco', iso_code: 'LC'},
      {name: 'Livorno', iso_code: 'LI'},
      {name: 'Lodi', iso_code: 'LO'},
      {name: 'Lucca', iso_code: 'LU'},
      {name: 'Macerata', iso_code: 'MC'},
      {name: 'Mantua', iso_code: 'MN'},
      {name: 'Massa', iso_code: 'an'},
      {name: 'Matera', iso_code: 'MT'},
      {name: 'Medio', iso_code: 'Ca'},
      {name: 'Messina', iso_code: 'ME'},
      {name: 'Milan', iso_code: 'MI'},
      {name: 'Modena', iso_code: 'MO'},
      {name: 'Monza', iso_code: 'an'},
      {name: 'Naples', iso_code: 'NA'},
      {name: 'Novara', iso_code: 'NO'},
      {name: 'Nuoro', iso_code: 'NU'},
      {name: 'Ogliastra', iso_code: 'OG'},
      {name: 'Olbia-Tempio', iso_code: 'OT'},
      {name: 'Oristano', iso_code: 'OR'},
      {name: 'Padua', iso_code: 'PD'},
      {name: 'Palermo', iso_code: 'PA'},
      {name: 'Parma', iso_code: 'PR'},
      {name: 'Pavia', iso_code: 'PV'},
      {name: 'Perugia', iso_code: 'PG'},
      {name: 'Pesaro', iso_code: 'an'},
      {name: 'Pescara', iso_code: 'PE'},
      {name: 'Piacenza', iso_code: 'PC'},
      {name: 'Pisa', iso_code: 'PI'},
      {name: 'Pistoia', iso_code: 'PT'},
      {name: 'Pordenone', iso_code: 'PN'},
      {name: 'Potenza', iso_code: 'PZ'},
      {name: 'Prato', iso_code: 'PO'},
      {name: 'Ragusa', iso_code: 'RG'},
      {name: 'Ravenna', iso_code: 'RA'},
      {name: 'Reggio', iso_code: 'Ca'},
      {name: 'Reggio', iso_code: 'Em'},
      {name: 'Rieti', iso_code: 'RI'},
      {name: 'Rimini[Note 2]', iso_code: 'RN'},
      {name: 'Rome', iso_code: 'RM'},
      {name: 'Rovigo', iso_code: 'RO'},
      {name: 'Salerno', iso_code: 'SA'},
      {name: 'Sassari', iso_code: 'SS'},
      {name: 'Savona', iso_code: 'SV'},
      {name: 'Siena', iso_code: 'SI'},
      {name: 'Sondrio', iso_code: 'SO'},
      {name: 'Syracuse', iso_code: 'SR'},
      {name: 'Taranto', iso_code: 'TA'},
      {name: 'Teramo', iso_code: 'TE'},
      {name: 'Terni', iso_code: 'TR'},
      {name: 'Trapani', iso_code: 'TP'},
      {name: 'Trento[Note 1]', iso_code: 'TN'},
      {name: 'Treviso', iso_code: 'TV'},
      {name: 'Trieste', iso_code: 'TS'},
      {name: 'Turin', iso_code: 'TO'},
      {name: 'Udine[Note 3]', iso_code: 'UD'},
      {name: 'Varese', iso_code: 'VA'},
      {name: 'Venice', iso_code: 'VE'},
      {name: 'Verbano-Cusio-Ossola', iso_code: 'VB'},
      {name: 'Vercelli', iso_code: 'VC'},
      {name: 'Verona', iso_code: 'VR'},
      {name: 'Vibo', iso_code: 'Va'},
      {name: 'Vicenza', iso_code: 'VI'},
      {name: 'Viterbo', iso_code: 'VT'}]},
    {
      name: 'USA', iso_code: 'US', state_label: 'State', states: [
      {'name': 'Alabama', 'iso_code': 'AL'},
      {'name': 'Alaska', 'iso_code': 'AK'},
      {'name': 'Arizona', 'iso_code': 'AZ'},
      {'name': 'Arkansas', 'iso_code': 'AR'},
      {'name': 'California', 'iso_code': 'CA'},
      {'name': 'Colorado', 'iso_code': 'CO'},
      {'name': 'Connecticut', 'iso_code': 'CT'},
      {'name': 'Delaware', 'iso_code': 'DE'},
      {'name': 'Florida', 'iso_code': 'FL'},
      {'name': 'Georgia', 'iso_code': 'GA'},
      {'name': 'Hawaii', 'iso_code': 'HI'},
      {'name': 'Idaho', 'iso_code': 'ID'},
      {'name': 'Illinois', 'iso_code': 'IL'},
      {'name': 'Indiana', 'iso_code': 'IN'},
      {'name': 'Iowa', 'iso_code': 'IA'},
      {'name': 'Kansas', 'iso_code': 'KS'},
      {'name': 'Kentucky', 'iso_code': 'KY'},
      {'name': 'Louisiana', 'iso_code': 'LA'},
      {'name': 'Maine', 'iso_code': 'ME'},
      {'name': 'Maryland', 'iso_code': 'MD'},
      {'name': 'Massachusetts', 'iso_code': 'MA'},
      {'name': 'Michigan', 'iso_code': 'MI'},
      {'name': 'Minnesota', 'iso_code': 'MN'},
      {'name': 'Mississippi', 'iso_code': 'MS'},
      {'name': 'Missouri', 'iso_code': 'MO'},
      {'name': 'Montana', 'iso_code': 'MT'},
      {'name': 'Nebraska', 'iso_code': 'NE'},
      {'name': 'Nevada', 'iso_code': 'NV'},
      {'name': 'New Hampshire', 'iso_code': 'NH'},
      {'name': 'New Jersey', 'iso_code': 'NJ'},
      {'name': 'New Mexico', 'iso_code': 'NM'},
      {'name': 'New York', 'iso_code': 'NY'},
      {'name': 'North Carolina', 'iso_code': 'NC'},
      {'name': 'North Dakota', 'iso_code': 'ND'},
      {'name': 'Ohio', 'iso_code': 'OH'},
      {'name': 'Oklahoma', 'iso_code': 'OK'},
      {'name': 'Oregon', 'iso_code': 'OR'},
      {'name': 'Pennsylvania', 'iso_code': 'PA'},
      {'name': 'Rhode Island', 'iso_code': 'RI'},
      {'name': 'South Carolina', 'iso_code': 'SC'},
      {'name': 'South Dakota', 'iso_code': 'SD'},
      {'name': 'Tennessee', 'iso_code': 'TN'},
      {'name': 'Texas', 'iso_code': 'TX'},
      {'name': 'Utah', 'iso_code': 'UT'},
      {'name': 'Vermont', 'iso_code': 'VT'},
      {'name': 'Virginia', 'iso_code': 'VA'},
      {'name': 'Washington', 'iso_code': 'WA'},
      {'name': 'West Virginia', 'iso_code': 'WV'},
      {'name': 'Wisconsin', 'iso_code': 'WI'},
      {'name': 'Wyoming', 'iso_code': 'WY'},
      {'name': 'American Samoa', 'iso_code': 'AS'},
      {'name': 'District of Columbia', 'iso_code': 'DC'},
      {'name': 'Federated States of Micronesia', 'iso_code': 'FM'},
      {'name': 'Guam', 'iso_code': 'GU'},
      {'name': 'Marshall Islands', 'iso_code': 'MH'},
      {'name': 'Northern Mariana Islands', 'iso_code': 'MP'},
      {'name': 'Palau', 'iso_code': 'PW'},
      {'name': 'Puerto Rico', 'iso_code': 'PR'},
      {'name': 'Virgin Islands', 'iso_code': 'VI'}]
    }]
};
